# Generated by Django 3.1.3 on 2020-11-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warzywniak', '0002_klienci_warzywa_zamowienia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
