# Generated by Django 3.1.3 on 2021-01-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warzywniak', '0003_delete_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warzywa',
            name='Cena_currency',
        ),
        migrations.RemoveField(
            model_name='zamowienia',
            name='id_Klienta',
        ),
        migrations.RemoveField(
            model_name='zamowienia',
            name='id_Warzywa',
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='Warzywa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='warzywniak.warzywa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='klient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='warzywniak.klienci'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warzywa',
            name='Cena',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='Data_Zamowienia',
            field=models.DateTimeField(),
        ),
    ]
